#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

PKG_NAME="linux"
PKG_VERSION="cuboxi-ceca32e904"
GIT_REPO="git://github.com/SolidRun/linux-linaro-stable-mx6.git"
DEST_DIR="$PKG_NAME"

echo "getting sources..."
echo " -- $DEST_DIR -- "
  if [ ! -d $DEST_DIR-latest ]; then
    git clone $GIT_REPO ./$DEST_DIR-latest
  fi

  cd $DEST_DIR-latest
    git pull
  cd ..

echo "copying sources..."
  rm -rf $PKG_NAME-$PKG_VERSION
  cp -R $DEST_DIR-latest $PKG_NAME-$PKG_VERSION
  #echo "$GIT_REV" > $PKG_NAME-$PKG_VERSION/VERSION

echo "cleaning sources..."
  rm -rf $PKG_NAME-$PKG_VERSION/.git

echo "packing sources..."
  tar cvJf $PKG_NAME-$PKG_VERSION.tar.xz $PKG_NAME-$PKG_VERSION

echo "remove temporary sourcedir..."
  rm -rf $PKG_NAME-$PKG_VERSION
  
echo "copying tar balls to sources..."
   if [ ! -d ../../sources/ ]; then
      mkdir ../../sources/
   fi
   if [ ! -d ../../sources/$PKG_NAME/ ]; then
      mkdir ../../sources/$PKG_NAME/
   fi
   mv $PKG_NAME-$PKG_VERSION.tar.xz ../../sources/$PKG_NAME/
echo "generate md5 and url files..."
   cd ../..
   md5sum sources/$PKG_NAME/$PKG_NAME-$PKG_VERSION.tar.xz > sources/$PKG_NAME/$PKG_NAME-$PKG_VERSION.tar.xz.md5
   echo " http://sources.openelec.tv/devel/$PKG_NAME-$PKG_VERSION.tar.xz" > sources/$PKG_NAME/$PKG_NAME-$PKG_VERSION.tar.xz.url
   echo "Source tar balls generated for $PKG_NAME PKG_VERSION=$PKG_VERSION successfully."
